controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_create:
    path: /user/create
    controller: App\Controller\UserController::create
    methods: [GET, POST]
